providers = ["python"]

[phases.setup]
nixPkgs = [
  "python3",
  "python3Packages.flask",
  "python3Packages.requests",
  "python3Packages.pyaudio",
  "python3Packages.pyttsx3",
  "python3Packages.speechrecognition",
  "python3Packages.flask-cors",
  "portaudio",
  "alsa-lib",
  "libffi",
  "libpulseaudio",
  "ffmpeg"
]

[phases.install]
cmds = [
    "python3 -c 'import flask, requests, pyaudio, pyttsx3, speech_recognition, flask_cors'"
]

[start]
cmd = "python app.py"
