[phases.setup]
nixPkgs = ["portaudio", "alsaLib", "libffi", "libpulseaudio", "ffmpeg"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "python app.py"
