providers = ["python"]

[phases.setup]
nixPkgs = [
  "python3",
  "python3Packages.pip",
  "portaudio",
  "alsa-lib",
  "libffi",
  "libpulseaudio",
  "ffmpeg"
]

[phases.install]
aptPkgs = [
  "python3-pip"
]
cmds = [
    "curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py",
    "python3 get-pip.py --user",
    "python3 -m pip install --user -r requirements.txt"
]

[start]
cmd = "python app.py"
