providers = ["python"]

[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.flask",
  "python311Packages.requests",
  "python311Packages.pyaudio",
  "python311Packages.pyttsx3",
  "python311Packages.speechrecognition",
  "python311Packages.flask_cors",
  "portaudio",
  "alsa-lib",
  "libffi",
  "libpulseaudio",
  "ffmpeg"
]

[phases.install]
installScript = """
PYTHONPATH="$PYTHONPATH:$(python3 -c 'import site; print(site.getsitepackages()[0])')"
python3 -c 'import flask, requests, pyaudio, pyttsx3, speech_recognition as sr, flask_cors'
"""

[start]
cmd = "python app.py"
