providers = ["python"]

[phases.setup]
nixPkgs = ["portaudio", "alsa-lib", "libffi", "libpulseaudio", "ffmpeg"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python app.py"
