providers = ["python"]

[phases.setup]
nixPkgs = [
  "python310",
  "python310Packages.pip",
  "python310Packages.virtualenv",
  "portaudio",
  "pkg-config",
  "alsa-lib",
  "libffi",
  "pulseaudio",
  "ffmpeg",
  "gcc",
  "python310Packages.pyaudio"
]

[phases.install]
installScript = """
python3 -m venv /app/venv
source /app/venv/bin/activate
sed -i '/PyAudio/d' requirements.txt
pip install --no-cache-dir -r requirements.txt
"""

[start]
cmd = "source /app/venv/bin/activate && python app.py"
